### ISSUE TITLE
After phone auth, how to ask user for username?

### ISSUE THREAD

**Issue by fdietze** [sam0829/firebase_auth_ui#11]
Thanks for the great library!

Phone auth has as displayName an empty string. Would it be possible to ask for it in the auth process, or should I do it manually after auth?

**Comment by sam0829** [comment]
@fdietze Hey, sorry for the delay in getting back. phone auth will only validate phone number and it won't ask for anything else. You'll need to implement that on your own. I am closing the issue assuming this isn't possible, but I'll take a deeper look over next week and re-open this if it's possible to achieve :)
