### ISSUE TITLE
Is it possible to get current user?

### ISSUE THREAD

**Issue by yamamotokotaro** [sam0829/firebase_auth_ui#12]
I tried sample program and I like this plugin.
But sample program doesn't get current user. 
Is this plugin support to get current user?

**Comment by robmr88** [comment]
Hi , you can get current user  using FirebaseAuth library ( https://pub.dev/packages/firebase_auth ) 
FirebaseAuthUi is mainly focused on giving you the login/registration process.

**Comment by sam0829** [comment]
Hi @yamamotokotaro , as @robmr88 suggested, you'll need to use firebase auth plugin in order to retrieve the full user details. I guess it'll be out of the scope of this plugin to expose full current user object and hence I am closing this issue.
