### ISSUE TITLE
Feature: Phone Authentication

### ISSUE THREAD

**Issue by GRBurst** [sam0829/firebase_auth_ui#3]
Thanks for this amazing package, it really reduces the authentication burden!

It would be really great if the authentication method by phone number would be added. For me it is still the best way to integrate contacts in my app.

Happy to hear from you!

**Comment by sam0829** [comment]
Hi @GRBurst Glad you find this useful.

And sure, will try to add this feature ASAP in the plugin. I am not sure about the timeline for releasing it though because I am super stuck with other projects ATM. Meanwhile if you get time, feel free to send a PR :)

**Comment by GRBurst** [comment]
👍

**Comment by flakerimi** [comment]
Where are you getting countries list. Kosovo is wrong code +383 should be.
