### ISSUE TITLE
new user sign up

### ISSUE THREAD

**Issue by cyberlahy** [sam0829/firebase_auth_ui#6]
Hi,
great package.
How can I know if this is a new user (sign up)? So I can insert him in firestore.
thanks

**Comment by sam0829** [comment]
Hi, unfortunately it looks like it's not possible to determine that directly. But since the plugin returns UID of user, you can query your firestore database to see if the user with same UID exists or not. And if not, you can insert the user data. I'll see if there's some way I can expose the boolean with `FirebaseUser`.

**Comment by cyberlahy** [comment]
But this will cost firestore extra reads every time an user sign in

**Comment by sam0829** [comment]
Yes that can be a problem. I checked again and I see there's hope for Android but couldn't find if iOS's native SDK exposes such boolean. Will keep you posted if I find something :)

**Comment by sam0829** [comment]
@cyberlahy I can confirm there's way to determine new users without querying for both the platforms. Will add a boolean property in my next update. Thanks for bringing this to attention.

**Comment by cyberlahy** [comment]
I see that metadata contains creationTime and lastSignInTime (same value if new user), if you can expose metadata inside FirebaseUser.
Maybe someone needs the client's  join date in their app also
thanks

**Comment by sam0829** [comment]
timestamp can't be used to determine new user as I read they aren't reliable sometime. However I do believe the metadata can be useful to others so I'll definitely look into exposing them as well.

**Comment by cyberlahy** [comment]
Thanks. You can close this issue. I will post a new for features or questions
